source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/yezi-kk/YWSpecs.git'        #私有仓库地址

target 'YWAnalytics_Example' do
  pod 'YWAnalytics', :path => '../'

  target 'YWAnalytics_Tests' do
    inherit! :search_paths

    
  end
end
